id: P71743651
initial_creation_type: ocr
source_metadata:
  volumes:
    84837b1496be4666b41716633b170a37:
      base_file: v037.txt
      image_group_id: I1PD95882
      title: འཕགས་པ་སྒོ་དྲུག་པའི་གཟུངས་ཀྱི་རྣམ་པར་བཤད་པ།
      total_pages: 1379
      volume_number: 37
